alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ', '(', ')', '.']

encryptedMessage = "xtzbia(ktuhktzria(kvtbltxtixbkth)txe.hkbmafltmaxmtzk(xm(tma(t(gzkrimbhgtxg tma(tk(o(klbg.t (zkrimbhgw"

decryptedMessage = ""

#create an algorithm (systematic way of solving a problem)
#that will decrypt the encoded message
#Assume that it was generated by replacing the original message
#letter by letter

